### ISSUE TITLE
Running cypress multiple times

### ISSUE THREAD

**Issue by jliebrand** [ksocha/cypress-circleci-reporter#8]
Hi there,

First of all, thanks for this reporter - sure makes life easier.

Just a quick question. We run cypress twice in our circleci job. The first time with:
--config 'viewportWidth=375,viewportHeight=667'

and then again with
--config 'viewportWidth=1024,viewportHeight=800'

the tests *should* not really change too much in timings, but will this setup cause problems with this reporter? E.g. should I keep the results of each run in a different directory so they dont conflict with one another?

**Comment by ksocha** [comment]
@jliebrand I'm very sorry for really late reply.
Probably you already figured that out, but you should save test result from separate runs in different directories.
