### ISSUE TITLE
Filename always reported as ""

### ISSUE THREAD

**Issue by svensson-david** [ksocha/cypress-circleci-reporter#9]
Hi!
I cannot figure out if I'm just missing some configuration or if I've encountered a bug.
I've added the reporter to my Cypress command on CircleCI and it is generating .xml-files in the test results folder.

However the report files are not including the file name of the spec, instead "file" is just empty.
Example below:
```
# test_results/cypress/cypress-5e9a03c5479c2136b2f0f8b114050eb8.xml
<testsuite name="cypress" timestamp="2020-11-02T13:14:06" time="11.3070" tests="4" failures="0" skipped="0">
    ...
    <testcase name="guest cannot see assignments" file="" time="0.8800" classname="Learning > Assignments.signed out"/>
    ...
</testsuite>
```

This leads CircleCI to output the following on the next run:
```
...
Autodetect no matching filename or classname.  If file names are used, double check paths for absolute vs relative.
Example input file: "cypress/integration/admin/course_versions_spec.js"
Example file from timings: ""
```

I tried switching to `--timings-type=classname` for `circleci tests split` but that didn't work either since the classnames stated in the reports file are not really class names.

Is this something you've encountered before?

**Comment by ksocha** [comment]
Hi!
Thanks for reaching me out. What is the version of Cypress that you currently use?

**Comment by svensson-david** [comment]
Hello @ksocha!
I'm currently running 3.4.1 if I'm not mistaken.

**Comment by ksocha** [comment]
One of my colleagues has the same kind of issue. It seems you have to update the version to [v3.8.3](https://github.com/cypress-io/cypress/releases/tag/v3.8.3) or newer to make it work.

**Comment by svensson-david** [comment]
Ok, awesome!
Will give it a try and let you know what I find 👍

**Comment by svensson-david** [comment]
@ksocha worked great!
Had to fix some specs that broke when upgrading but other than that no issues.

I'm closing the issue.
Please let me know if there's anything I can do to help with the project in the future and thanks again!
